---
  - name: Get admin password
    shell: cat '/var/lib/jenkins/secrets/initialAdminPassword'
    register: initialAdminPassword

  - name: Restart Jenkins to make the plugin data available
    service: name=jenkins state=restarted

  - name: Wait untils Jenkins web API is available
    shell: curl --head --silent http://localhost:8080/cli/
    register: result
    until: result.stdout.find("403") != -1
    retries: 12
    delay: 5

  - name: Install jobs
    jenkins_job:
      config: "{{ lookup('file', 'files/jenkins-test-webapp.xml') }}"
      name: jenkins-test-webapp
      password: "{{ initialAdminPassword.stdout }}"
      url: http://localhost:8080
      user: admin
