---
- hosts: localhost
  become: yes
  tasks:
    - name: Install jobs
      jenkins_job:
        config: "{{ lookup('file', 'templates/jenkins-test-webapp.xml') }}"
        name: jenkins-test-webapp
        password: xxxxxxxxxxxxxxxxxxxxxxxx
        url: http://localhost:8080
        user: admin
